### ISSUE TITLE
Correct docs about how to configure harbor

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/docs.kubesphere.io#76]
https://docs.kubesphere.io/express/zh-CN/manage-imageregistries/  

 - 创建 Harbor 镜像仓库

pls add more content to tell users what to do if no daemon.json existed:  
user should create daemon.json manually and add configuration like below:  
{  
"insecure-registries": ["ip-addr:port"]  
}

**Comment by FeynmanZhou** [comment]
@calvinyv  The document of how to manage registry has been modified and daemon.json already been discarded within this change. Since this case was only available in Docker-only scenario but not in KubeSphere env. It may be caused by the Startup parameters conflicts of the daemon file changes. Please see the up-to-date docs as following, it was passed after our test.
https://docs.kubesphere.io/express/zh-CN/manage-imageregistries/
